// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxPXMCG92bYmZPx-T1dUuXfydGr39Dcak',
    appId: '1:194506562240:web:349ee5529cc7cfbaf0eb25',
    messagingSenderId: '194506562240',
    projectId: 'task-731f6',
    authDomain: 'task-731f6.firebaseapp.com',
    storageBucket: 'task-731f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJw9c-YU8qHv1dkimk3Yy8MYGvOBr-7_M',
    appId: '1:194506562240:android:214d785e20ed59f1f0eb25',
    messagingSenderId: '194506562240',
    projectId: 'task-731f6',
    storageBucket: 'task-731f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAU489tYWkmblQvLFOxNq7qgYenBJGJUY',
    appId: '1:194506562240:ios:7d1f8cbc7023d3ccf0eb25',
    messagingSenderId: '194506562240',
    projectId: 'task-731f6',
    storageBucket: 'task-731f6.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAU489tYWkmblQvLFOxNq7qgYenBJGJUY',
    appId: '1:194506562240:ios:7d1f8cbc7023d3ccf0eb25',
    messagingSenderId: '194506562240',
    projectId: 'task-731f6',
    storageBucket: 'task-731f6.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );
}
